language: scala
sudo: false

scala: 2.12.3

jdk: oraclejdk8

script:
  - sbt ++$TRAVIS_SCALA_VERSION samples/compile test
  - $(npm bin)/tsc samples/*.d.ts

before_cache:
  # See http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install 8
  - nvm use 8
  - npm install typescript@2.6.2

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - node_modules
